import { Inter, Geist_Mono } from "next/font/google"; // Import Inter
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import Provider from "./provider";
import { Toaster } from "sonner";

// Configure Inter font with variable weights
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Assign CSS variable
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Specify weights
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
        <ClerkProvider>
      <body
        // Apply Inter variable alongside Geist Mono
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >

            <Provider>
              <div>{children}</div>
            </Provider>
            <Toaster/>
   
      </body>
      </ClerkProvider>
    </html>
  );
}
